models:
  Models\Product:
    name: string:191
    description: string:191
    barcode: string:191 nullable
    purchase_price: decimal:10,2
    sale_price: decimal:10,2
    unit: string:191
    quantity_in_stock: integer
    minimum_quantity_in_stock: integer

controllers:
  Admin\Product:
    index:
      query: all
      render: admin.products.index with:products

    create:
      render: admin.products.create with:product

    store:
      validate: name, description, barcode, purchase_price, sale_price, unit, quantity_in_stock, minimum_quantity_in_stock
      save: product
      redirect: admin.products.index

    show:
      render: admin.products.show with:product

    edit:
      render: admin.products.edit with:product

    update:
      validate: name, description, barcode, purchase_price, sale_price, unit, quantity_in_stock, minimum_quantity_in_stock
      save: product
      redirect: admin.products.index

    destroy:
      delete: product
